############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

# main menu
[[main]]
name = "CV"
url = "curriculum-vitae/"
weight = 2

[[main]]
name = "Publications"
url = "publications/"
weight = 3

[[main]]
name = "Articles - GR"
url = "articles/"
weight = 4

[[main]]
name = "Services"
url = "services/"
weight = 5
hasChildren = true

  [[main]]
  parent = "Services"
  name = "Coronary Vessel Surgery"
  url = "services/surgery-coronary-vessel"
  weight = 1

  [[main]]
  parent = "Services"
  name = "Heart Valve Surgery"
  url = "services/heart-valve"
  weight = 2

  [[main]]
  parent = "Services"
  name = "Thoracic aortic surgery"
  url = "services/thoracic-aortic-surgery"
  weight = 3

  [[main]]
  parent = "Services"
  name = "Artificial heart"
  url = "services/artificial-heart"
  weight = 4
  
[[main]]
name = "Wikipedia"
url = "https://www.wikipedia.org/"
weight = 6

# footer menu
[[footer]]
name = "Henry Dunant Hospital"
url = "https://www.dunant.gr/en/"
weight = 1
