############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 4

[[main]]
name = "Blog"
url = "blog/"
weight = 7


[[main]]
name = "Services"
url = "services/"
weight = 10
hasChildren = true

  [[main]]
  parent = "Services"
  name = "Coronary Vessel Surgery"
  url = "services/surgery-coronary-vessel"
  weight = 1

  [[main]]
  parent = "Services"
  name = "Heart Valve Surgery"
  url = "services/heart-valve"
  weight = 2

  [[main]]
  parent = "Services"
  name = "Thoracic aortic surgery"
  url = "services/thoracic-aortic-surgery"
  weight = 3

  [[main]]
  parent = "Services"
  name = "Artificial heart"
  url = "services/artificial-heart"
  weight = 4

[[main]]
weight = 9
name = "Pages"
hasChildren = true

  [[main]]
  parent = "Pages"
  name = "Changelog"
  url = "changelog/"
  weight = 9

  [[main]]
  parent = "Pages"
  name = "Elements"
  url = "elements/"
  weight = 11
  
[[main]]
name = "Wikipedia"
url = "https://www.wikipedia.org/"
weight = 15


# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1
