#################### default parameters ################################
# favicon
favicon = "images/favicon.png"
# logo
logo = "images/logo.svg"
# use `x` with logo_width, example: "100x"
logo_width = "240x"
# logo text will only show when logo is missing.
logo_text = "Dr. med. Bairaktaris"
# image gallery shortcode
image_gallery = true

# footer information
footer_info = "Lorem ipsum dolor sit sed dmi amet, consectetur adipiscing. Cdo tellus, sed condimentum volutpat."

# contact form action
contact_form_action = "" # contact form works with https://formspree.io

# career form action
career_form_action = "#" # career form works with https://formspree.io

# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>" 
custom_script= "" 

# Main Sections
mainSections= ["articles"]

# contact information
[contact_info]
phone = ["+30 698 466 0319"]
email = ["andreas@bairaktaris.de"]

# imaging processing
[imaging]
# Default JPEG or WebP quality setting. Default is 100.
quality = 100

# Preloader
[preloader]
enable = true
preloader = "images/favicon.png" # use jpg, png, svg or gif format.

# Navigation button
[navigation_button]
enable = true
label = "Make an appointment"
link = "contact/"

# seo meta data for OpenGraph / Twitter Card
[metadata]
keywords = ["Bairaktaris Andreas", "Cardiothoracic Surgeon"]
description = "Software and SAAS Landing Hugo Theme"
author = "Andreas Bairaktaris"
image = "images/og-image.jpg" # this image will be used as fallback if a page has no image of its own

# matomo tracking: see https://matomo.org/
[matomo]
enable = false
url = "" # your matomo url
id = "" # your matomo id

# baidu analytics: see https://tongji.baidu.com/
[baidu]
enable = false
analytics_id = "" # Your ID

# plausible analytics: see https://plausible.io/
[plausible]
enable = false
domain = "" # yourdomain.com

# counter analytics: see https://counter.dev/setup.html
[counter]
enable = true
username = "meesvandongen" # your username

# site verifications
[site_verification]
google = "" # Your verification code
bing = "" # Your verification code
baidu = "" # Your verification code
facebook = "" # Your verification code

# cookies
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

# call-to-action
[cta]
enable = true
title = "The health of the patient at the center."
content = "Specialized cardiac surgery services, combined with the most modern equipment and high quality care facilities"
button = "Make an appointment"
button_link = "contact/"

############################# social site ########################
[[social]]
title = "Andreas Bairaktaris"
icon = "lab la-facebook-f" # https://icons8.com/line-awesome
link = "https://www.facebook.com/andreas.bairaktaris"

[[social]]
title = "Andreas Dr. Bairaktaris"
icon = "lab la-linkedin-in" # https://icons8.com/line-awesome
link = "https://www.linkedin.com/in/andreas-dr-bairaktaris-4149a178/"
